### ISSUE TITLE
Plugin does not appear in the list

### ISSUE THREAD

**Issue by mvrinaldi** [avollkopf/cbpi4-PIDAutoTune#1]
I installed this (and other plugins like FLowmeter) and everything went fine (as explained in this gitbook: https://openbrewing.gitbook.io/craftbeerpi4_support/master/plugin-installation)

After installation, I activated the plugin (cbpi add cbpi4-PID_AutoTune) and activated normally (at least message indicates activation of the plugin). However, it doesn't appear in the plugin list and it doesn't appear in the kettle settings either.

I have CBPI version 4.0.0.41

**Comment by avollkopf** [comment]
The cbpi add command is currently not failsafe... If you type the wrong name for a plugin, the add command does not care. 
what is the output if you type `sudo cbpi plugins` and `sudo pip3 list | grep cbpi4`?

**Comment by mvrinaldi** [comment]
So the problem was this.

I must have been writing something wrong and as the message was that it was activated, I didn't notice the error.

I redid the activation process and now it appears in the list of Cbpi plugins. But the configuration does not appear on the kettle.

![plug](https://user-images.githubusercontent.com/11636818/140568582-1ea71d40-3e3f-4f8a-871a-c3fa0d4fe704.jpg)
![hist](https://user-images.githubusercontent.com/11636818/140568643-b5ee0279-3047-44f0-845b-e4c1d3bc53be.jpg)



**Codes results:**

pi@raspberrypi:~ $ sudo cbpi plugins

List of active plugins
- (0.0.20) cbpi4ui
No package metadata was found for FLowmeter

--------------------------------------

pi@raspberrypi:~ $ sudo pip3 list | grep cbpi4
cbpi4-Flowmeter         0.0.1      
cbpi4-PID-AutoTune      0.0.4      
cbpi4-PushOver          0.0.3      
cbpi4ui                 0.0.20

**Comment by mvrinaldi** [comment]
I saw that there are some differences in the plugin name and in the result of pip3 list | grep cbpi4:

cbpi4-PID_AutoTune (underline)
and
cbpi4-PID-AutoTune (hyphen)

That's probably it. I will try again soon and post here.

**Comment by avollkopf** [comment]
The Flowmeter Plugin has not been added correctly -> FLowmeter instead cbpi4-Flowmeter

And it seems to be that the other plugin has not been added.

**Comment by mvrinaldi** [comment]
I tried both ways and neither of them activated the plugin. 

cbpi add cbpi4-PID_Autotune
and
cbpi add cbpi4-PID-Autotune

I only have to reinstall everything

**Comment by mvrinaldi** [comment]
I solved the problem by reinstalling everything (including Ubuntu)
