### ISSUE TITLE
Plugin doesn't appear in the hardware configs

### ISSUE THREAD

**Issue by mvrinaldi** [avollkopf/cbpi4-PIDAutoTune#2]
I'm opening another post because the problem now is different and I thought it best to open another to organize, in case someone has the same problem. 

The plugin is enabled correctly (I think)

pi@raspberrypi:~ $ sudo cbpi plugins
List of active plugins
- (0.0.20)	cbpi4ui
- (0.0.4)	cbpi4-PID-AutoTune
- (0.0.3)	cbpi4-PushOver

 but does not appear in the kettle settings

![hysterese](https://user-images.githubusercontent.com/11636818/140596066-96cf2a73-341f-440c-9d4b-b7913f76f35e.jpg)

**Comment by avollkopf** [comment]
I am currently traveling and can't really support. Once I am back, I will try to rename it in a first step. But I also need to align with pypi as the name without - or _ was not available.

**Comment by mvrinaldi** [comment]
I really appreciate your help!!! No problem with timing. You are already doing a lot for us homebrewers!!!

**Comment by avollkopf** [comment]
I just updated the instructions and installed it with these commands directly from gtihub and activatd the plugin. The plugin is showing up on my test system.

**Comment by mvrinaldi** [comment]
Thanks Alexander. Now, I'm traveling... lol... As soon as I arrive I try again.

**Comment by avollkopf** [comment]
No worries as I also won't be available for the next couple of days......

**Comment by mvrinaldi** [comment]
Alexander... I really appreciate your help!!! The installation via pypi.org didn't work (didn't appear in the settings) but the installation via GIT REPO worked perfectly!!! Thank you a lot!!!
